name: classic_tailwind
display_name: Classic with Tailwind
version: 1.0.0
author:
  name: "Jordan Morlet"
  email: "itdev@naturamedicatrix.lu"

parent: classic
assets:
  use_parent_assets: true
  css:
    all:
      - id: css-variables
        path: assets/css/variables.css
        media: all
        priority: 40
      - id: tailwind-styles
        path: assets/css/tailwind.css
        media: all
        priority: 50
      - id: custom-header-styles
        path: assets/css/custom-header.css
        media: all
        priority: 60
      - id: custom-advantages-styles
        path: assets/css/custom-advantages.css
        media: all
        priority: 63
      - id: custom-footer-styles
        path: assets/css/custom-footer.css
        media: all
        priority: 65
      - id: main-styles
        path: assets/css/main.css
        media: all
        priority: 70
  js:
    all:
      - id: text-carousel
        path: assets/js/text-carousel.js
        priority: 30
      - id: footer-accordion
        path: assets/js/footer-accordion.js
        priority: 35