<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuQIqbwltN0OZIaobuTPr'."\n".'nibL0LdfKHDfm6/PkX6pAz1vIoFz+eRoveKkF4Grpnhqh8ZjH3Jz6QwLPU0ww813'."\n".'EMReUXxxvPZmrKkW9B5/s6vA5HwktJembRIMZYNuaZsR9gw8p6L5cW5gDJhk9TX0'."\n".'z1Jaw2LBHXV758GdtBnEG/+2T3CZqnffcxaQ7uolBaSYCmoIGZpdia2HvLd3cLyR'."\n".'Q0CPkYfcFdkPgCiyD0KXnPIeaYN6xP4OA7b9DE6FfRJC35/yppSZs1AQXmK4lRG/'."\n".'pOHgX3rG4+VDbs5b69ThwKgwOgVG4AXfTK0gxr7XOnU/37vDoQCCNRcnuybDuLwP'."\n".'0QIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
