name: theme_naturamedicatrix
display_name: Theme Naturamedicatrix
version: 1.0.0
author:
  name: "Naturamedicatrix"
  email: "itdev@naturamedicatrix.lu"

parent: classic
assets:
  use_parent_assets: true
  css:
    all:
      - id: css-variables
        path: assets/css/variables.css
        media: all
        priority: 70
      - id: tailwind-styles
        path: assets/css/tailwind.css
        media: all
        priority: 70
      - id: custom-header-styles
        path: assets/css/custom-header.css
        media: all
        priority: 70
      - id: custom-advantages-styles
        path: assets/css/partials/custom-advantages.css
        media: all
        priority: 70
      - id: custom-footer-styles
        path: assets/css/custom-footer.css
        media: all
        priority: 70
      - id: authentication-styles
        path: assets/css/pages/custom-authentication.css
        media: all
        priority: 70
      - id: custom-forget-password-styles
        path: assets/css/pages/custom-forget-password.css
        media: all
        priority: 70
      - id: custom-registration-styles
        path: assets/css/pages/custom-registration.css
        media: all
        priority: 70
      - id: custom-aside-container-styles
        path: assets/css/aside-container.css
        media: all
        priority: 70
      - id: custom-contact-styles
        path: assets/css/pages/custom-contact.css
        media: all
        priority: 70
      - id: custom-brands-styles
        path: assets/css/pages/custom-brands.css
        media: all
        priority: 70
      - id: main-styles
        path: assets/css/main.css
        media: all
        priority: 100
  js:
    all:
      - id: text-carousel
        path: assets/js/text-carousel.js
        priority: 70
      - id: footer-accordion
        path: assets/js/footer-accordion.js
        priority: 70
      - id: password-toggle
        path: assets/js/password-toggle.js
        priority: 70