<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCTZ6CQM\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCTZ6CQM/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCTZ6CQM.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCTZ6CQM\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerCTZ6CQM\appAppKernelDevDebugContainer([
    'container.build_hash' => 'CTZ6CQM',
    'container.build_id' => '3a0c3605',
    'container.build_time' => 1744201576,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCTZ6CQM');
