<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO1EeqX4\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO1EeqX4/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO1EeqX4.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO1EeqX4\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerO1EeqX4\appAppKernelDevDebugContainer([
    'container.build_hash' => 'O1EeqX4',
    'container.build_id' => '418a9ef4',
    'container.build_time' => 1744115719,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO1EeqX4');
